/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "models.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ProtobufModels_DigitalSensor, ProtobufModels_DigitalSensor, AUTO)


PB_BIND(ProtobufModels_AnalogSensor, ProtobufModels_AnalogSensor, AUTO)


PB_BIND(ProtobufModels_Sensor, ProtobufModels_Sensor, AUTO)


PB_BIND(ProtobufModels_Sensors, ProtobufModels_Sensors, 2)



