/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_PROTOBUFMODELS_MODELS_PB_H_INCLUDED
#define PB_PROTOBUFMODELS_MODELS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ProtobufModels_AnalogSensor {
    int32_t UpperRange;
    int32_t LowerRange;
    float Value;
} ProtobufModels_AnalogSensor;

typedef struct _ProtobufModels_DigitalSensor {
    int32_t Timestamp;
    bool Value;
} ProtobufModels_DigitalSensor;

typedef struct _ProtobufModels_Sensor {
    pb_size_t which_Type;
    union {
        ProtobufModels_DigitalSensor Digital;
        ProtobufModels_AnalogSensor Analog;
    } Type;
    char MeasurementUnit[4];
    int32_t Pin;
} ProtobufModels_Sensor;

typedef struct _ProtobufModels_Sensors {
    pb_size_t List_count;
    ProtobufModels_Sensor List[16];
    int32_t Timestamp;
} ProtobufModels_Sensors;


/* Initializer values for message structs */
#define ProtobufModels_DigitalSensor_init_default {0, 0}
#define ProtobufModels_AnalogSensor_init_default {0, 0, 0}
#define ProtobufModels_Sensor_init_default       {0, {ProtobufModels_DigitalSensor_init_default}, "", 0}
#define ProtobufModels_Sensors_init_default      {0, {ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default, ProtobufModels_Sensor_init_default}, 0}
#define ProtobufModels_DigitalSensor_init_zero   {0, 0}
#define ProtobufModels_AnalogSensor_init_zero    {0, 0, 0}
#define ProtobufModels_Sensor_init_zero          {0, {ProtobufModels_DigitalSensor_init_zero}, "", 0}
#define ProtobufModels_Sensors_init_zero         {0, {ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero, ProtobufModels_Sensor_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProtobufModels_AnalogSensor_UpperRange_tag 1
#define ProtobufModels_AnalogSensor_LowerRange_tag 2
#define ProtobufModels_AnalogSensor_Value_tag    3
#define ProtobufModels_DigitalSensor_Timestamp_tag 1
#define ProtobufModels_DigitalSensor_Value_tag   2
#define ProtobufModels_Sensor_Digital_tag        1
#define ProtobufModels_Sensor_Analog_tag         2
#define ProtobufModels_Sensor_MeasurementUnit_tag 3
#define ProtobufModels_Sensor_Pin_tag            4
#define ProtobufModels_Sensors_List_tag          1
#define ProtobufModels_Sensors_Timestamp_tag     2

/* Struct field encoding specification for nanopb */
#define ProtobufModels_DigitalSensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    Timestamp,         1) \
X(a, STATIC,   SINGULAR, BOOL,     Value,             2)
#define ProtobufModels_DigitalSensor_CALLBACK NULL
#define ProtobufModels_DigitalSensor_DEFAULT NULL

#define ProtobufModels_AnalogSensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    UpperRange,        1) \
X(a, STATIC,   SINGULAR, INT32,    LowerRange,        2) \
X(a, STATIC,   SINGULAR, FLOAT,    Value,             3)
#define ProtobufModels_AnalogSensor_CALLBACK NULL
#define ProtobufModels_AnalogSensor_DEFAULT NULL

#define ProtobufModels_Sensor_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Type,Digital,Type.Digital),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Type,Analog,Type.Analog),   2) \
X(a, STATIC,   SINGULAR, STRING,   MeasurementUnit,   3) \
X(a, STATIC,   SINGULAR, INT32,    Pin,               4)
#define ProtobufModels_Sensor_CALLBACK NULL
#define ProtobufModels_Sensor_DEFAULT NULL
#define ProtobufModels_Sensor_Type_Digital_MSGTYPE ProtobufModels_DigitalSensor
#define ProtobufModels_Sensor_Type_Analog_MSGTYPE ProtobufModels_AnalogSensor

#define ProtobufModels_Sensors_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  List,              1) \
X(a, STATIC,   SINGULAR, INT32,    Timestamp,         2)
#define ProtobufModels_Sensors_CALLBACK NULL
#define ProtobufModels_Sensors_DEFAULT NULL
#define ProtobufModels_Sensors_List_MSGTYPE ProtobufModels_Sensor

extern const pb_msgdesc_t ProtobufModels_DigitalSensor_msg;
extern const pb_msgdesc_t ProtobufModels_AnalogSensor_msg;
extern const pb_msgdesc_t ProtobufModels_Sensor_msg;
extern const pb_msgdesc_t ProtobufModels_Sensors_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtobufModels_DigitalSensor_fields &ProtobufModels_DigitalSensor_msg
#define ProtobufModels_AnalogSensor_fields &ProtobufModels_AnalogSensor_msg
#define ProtobufModels_Sensor_fields &ProtobufModels_Sensor_msg
#define ProtobufModels_Sensors_fields &ProtobufModels_Sensors_msg

/* Maximum encoded size of messages (where known) */
#define ProtobufModels_DigitalSensor_size        13
#define ProtobufModels_AnalogSensor_size         27
#define ProtobufModels_Sensor_size               45
#define ProtobufModels_Sensors_size              763

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
